name: Benchmark
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bench:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.8'
          cache: true

      - name: setup re2 for cgo
        run: sudo apt-get update && sudo apt-get install -y libre2-dev

      - run: go run mage.go benchall

      - run: go run mage.go wafbenchall

      - uses: actions/upload-artifact@v3
        with:
          name: results
          path: build/*bench*.txt
